import type { Metadata } from "next";
import "./globals.css";
import { Montserrat } from "next/font/google"
import Footer from "@/components/footer";
import { CartProvider } from "./context/CartContext";
import Header from "@/components/header";
import HeadLine from "@/components/headline";
import { WishlistProvider } from "./context/wishlistContext";


const font = Montserrat({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={font.className}
      >
        <HeadLine/>
        <WishlistProvider>
        <CartProvider>
          <Header />

          {children}

        </CartProvider>
        </WishlistProvider>

        <Footer />
      </body>
    </html>
  );
}
